### ISSUE TITLE
Smile FAQ missing?

### ISSUE THREAD

**Issue by htmldoug** [FasterXML/smile-format-specification#2]
File appears missing: https://github.com/FasterXML/smile-format-specification/blame/master/README.md#L22

**Comment by cowtowncoder** [comment]
Yes. I am not sure if I had actual FAQ entries at fasterxml site; but since that is gone for good now (there may be an archive but... not something I can easily access now), just added one entry as placeholder.

But also added a link or two in README -- feel free to suggest improvements, links etc if you know of some. I know for example that Smile is used by Elastic, Solr, but not sure if there is good documentation to link to (or just something detailing benefits)
